### PR TITLE
quick proposal of fake driver for testing

### PR DESCRIPTION
**Pull request by maximehuylebroeck**
### 🔗 Linked issue

https://github.com/adonisjs/core/discussions/3833

### ❓ Type of change

- [ ] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [x] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

Created an extra driver with an in memory limiter to be able to test without redis/db's setup
So ideally in your .env.test you'll have the limiter driver on "fake" (or in the config) and it should work as any other driver.

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by maximehuylebroeck** [comment]
one small caveat is that the response of the remaining is negative in the fake.test.spec but I think this is a bug and I already created a ticket for that in the other project.

**Comment by thetutlage** [comment]
I think, we should opt for [the existing fakes API](https://docs.adonisjs.com/guides/testing/fakes) and add a `Limiter.fake()` method that switch to the memory driver and calling `Limiter.restore()` restores to the original set of drivers.

**Comment by maximehuylebroeck** [comment]
> I think, we should opt for [the existing fakes API](https://docs.adonisjs.com/guides/testing/fakes) and add a `Limiter.fake()` method that switch to the memory driver and calling `Limiter.restore()` restores to the original set of drivers.

I agree was trying to figure out how it was done in the other addons, will try to change it when I have some time. I'll try to just add the in memory driver here and i'll create an other pull request for the one with the fake api.

**Comment by maximehuylebroeck** [comment]
fyi @thetutlage they accepted my pr for the issue with the negative remaining, I'll update the dependency here as well. (https://github.com/animir/node-rate-limiter-flexible/issues/172)

**Pull request closed without merging**
